mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

  type-aliases-package: com.woniu.entity
spring:
  mvc:
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    cache: false
  redis:
    database: 0
    host: 192.168.7.54
    port: 6379

    timeout: 5
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 1


  application:
    name: WONIU58-OTHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ls?serverTimezone=GMT
    username: root
    password: 123456
server:
  port: 9300
eureka:
  client:
    service-url:
      defaultZone: http://192.168.7.54:9001/eureka/
  instance:
    instance-id: consumeHy-9322
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
ribbon:
  eureka:
    enabled: true
feign:
  hystrix:
    enabled: true

